# Generated by Django 5.0.1 on 2024-01-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hostel.basemodel')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('isFeatured', models.BooleanField(default=False)),
            ],
            bases=('hostel.basemodel',),
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hostel.basemodel')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(max_length=256)),
                ('isAvailable', models.BooleanField(default=True)),
                ('minPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('hostel.basemodel',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hostel.basemodel')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('isAvailable', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hostelItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
            ],
            bases=('hostel.basemodel',),
        ),
        migrations.CreateModel(
            name='AmenityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='amenities')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hostel')),
                ('isFeatured', models.BooleanField(default=False)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
            ],
        ),
        migrations.AddField(
            model_name='amenity',
            name='hostelItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room')),
            ],
        ),
    ]
