# Generated by Django 5.0.1 on 2024-01-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
