# Generated by Django 5.0.1 on 2024-01-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookings.basemodel')),
                ('name', models.CharField(max_length=256)),
                ('guardian_name', models.CharField(max_length=256)),
                ('student_id', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('guardian_mobile', models.CharField(max_length=10)),
                ('student_id_image', models.ImageField(upload_to='student')),
                ('payment_draft', models.ImageField(upload_to='payment')),
            ],
            bases=('bookings.basemodel',),
        ),
    ]
